system: base16
slug: Norion
name: Norion
author: tophc7
variant: dark
palette:
  base00: "320c0c"
  base01: "79312f"
  base02: "c03b38"
  base03: "fe7463"
  base04: "F09E75"
  base05: "F4B190"
  base06: "fff0e6"
  base07: "fff0e6"
  base08: "EE2E00" # Red
  base09: "F7A94E" # Orange
  base0A: "FCEEA1" # Yellow
  base0B: "8DE364" # Green
  base0C: "59A3C0" # Cyan
  base0D: "2B57B6" # Blue
  base0E: "AC92BF" # Purple
  base0F: "EA5E79" # Magenta

# https://coolors.co/320c0c-79312f-c03b38-fe7463-f2a882-ffd7c3-fff0e6-fff0e6
# https://coolors.co/ee2e00-f7a94e-2b57b6-8de364-59a3c0-fceea1-ac92bf-ea5e79
