# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."comfy" = {
    image = "corundex/comfyui-rocm:latest";
    environment = {
      "CUDA_VISIBLE_DEVICES" = "";
      "HIP_VISIBLE_DEVICES" = "0";
      "HSA_OVERRIDE_GFX_VERSION" = "11.0.0";
      "MODEL_DOWNLOAD" = "none";
      "PYTORCH_HIP_ALLOC_CONF" = "expandable_segments:True";
      "PYTORCH_TUNABLEOP_ENABLED" = "1";
      "TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL" = "1";
    };
    volumes = [
      "/store/ai-inputs:/workspace/ComfyUI/input:rw"
      "/store/ai-models:/workspace/ComfyUI/models:rw"
      "/store/ai-outputs:/workspace/ComfyUI/output:rw"
      "/store/comfyui/ComfyUI-Manager:/workspace/ComfyUI/custom_nodes/ComfyUI-Manager:rw"
      "/store/comfyui/cache:/root/.cache:rw"
      "/store/comfyui/custom_nodes:/workspace/ComfyUI/custom_nodes:rw"
      "/store/comfyui/user:/workspace/ComfyUI/user:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--device=/dev/kfd:/dev/kfd:rwm"
      "--memory=34359738368b"
      "--network-alias=comfy"
      "--network=ai-network"
      "--security-opt=seccomp:unconfined"
      "--shm-size=8589934592"
    ];
  };
  systemd.services."docker-comfy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ai-network.service"
    ];
    requires = [
      "docker-network-ai-network.service"
    ];
    partOf = [
      "docker-compose-comfy-root.target"
    ];
    wantedBy = [
      "docker-compose-comfy-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-ai-network" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f ai-network";
    };
    script = ''
      docker network inspect ai-network || docker network create ai-network
    '';
    partOf = [ "docker-compose-comfy-root.target" ];
    wantedBy = [ "docker-compose-comfy-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-comfy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
