# Build Service Factory
#
# Creates systemd services and timers for automated package builds.
# Generates Fish scripts with logging, notifications, and build logic.
#
# This file exports a function that other modules import and call.
#
# Usage in consuming modules:
#   let
#     builds = import ./lib.nix { inherit lib pkgs secrets host; };
#   in
#   builds.mkBuildService { ... }
#
{
  lib,
  pkgs,
  secrets,
  host,
}:
let
  # Shared configuration
  serviceUser = host.user.name;
  appriseUrl = "${secrets.service.discord.lenix}?avatar=no&footer=no";
in
{
  # Factory function for build services
  mkBuildService =
    {
      name,
      description,
      repoPath,
      packages,
      schedule,
      updateFlakeLock ? true,
      flakeInput ? null, # null = all inputs, string = specific input
      timeout ? "4h",
      emoji ? "📦",
      branch ? "main",
      # Optional: upstream check for specific input (for kernels)
      upstreamFlake ? null, # e.g., "github:xddxdd/nix-cachyos-kernel/release"
      upstreamInputName ? null, # e.g., "nix-cachyos-kernel"
      # Optional: run after another service completes (prevents concurrent builds)
      after ? null, # e.g., "kernel-builder"
    }:
    let
      packageList = lib.concatStringsSep " " packages;
      shortName = lib.replaceStrings [ "-builder" ] [ "" ] name;

      buildScript = pkgs.writeTextFile {
        name = "${name}.fish";
        executable = true;
        text = ''
          #!${lib.getExe pkgs.fish}
          #
          # ${description}
          # Auto-generated by mkBuildService
          #

          # Global configuration
          set -g repo_path "${repoPath}"
          set -g apprise_url "${appriseUrl}"
          set -g log_prefix "[${name}]"
          set -g packages ${packageList}
          set -g emoji "${emoji}"
          set -g branch "${branch}"

          #───────────────────────────────────────────────────────────────
          # Helper Functions
          #───────────────────────────────────────────────────────────────

          function log
            echo (date "+%Y-%m-%d %H:%M:%S") "$log_prefix" $argv
          end

          function log_error
            echo (date "+%Y-%m-%d %H:%M:%S") "$log_prefix ERROR:" $argv >&2
          end

          function notify
            set -l body $argv[1]
            printf '%s' "$body" | ${lib.getExe pkgs.apprise} -vv "$apprise_url"
            or log "Failed to send notification (non-critical)"
          end

          # Check if a package is built in the nix store
          function pkg_in_cache
            set -l pkg $argv[1]
            ${lib.getExe pkgs.nix} path-info --impure --expr "
              let
                flake = builtins.getFlake \"path:$repo_path\";
                pkgs = import flake.inputs.nixpkgs {
                  system = \"x86_64-linux\";
                  overlays = [ flake.overlays.default ];
                };
              in pkgs.$pkg
            " >/dev/null 2>&1
            return $status
          end

          # Build a package
          function build_pkg
            set -l pkg $argv[1]
            ${lib.getExe pkgs.nix} build --impure --no-link -L --expr "
              let
                flake = builtins.getFlake \"path:$repo_path\";
                pkgs = import flake.inputs.nixpkgs {
                  system = \"x86_64-linux\";
                  overlays = [ flake.overlays.default ];
                };
              in pkgs.$pkg
            "
            return $status
          end

          #───────────────────────────────────────────────────────────────
          # Main Script
          #───────────────────────────────────────────────────────────────

          # Ensure we're in the repo
          if not test -d "$repo_path"
            log_error "Repository not found: $repo_path"
            exit 1
          end

          cd "$repo_path"; or begin
            log_error "Failed to cd to $repo_path"
            exit 1
          end

          log "Starting ${shortName} build check..."

          # Fetch latest from remote
          log "Fetching latest changes from origin..."
          git fetch origin; or begin
            log_error "Failed to fetch from origin"
            exit 1
          end

          # Pull any changes
          git pull --ff-only origin $branch; or begin
            log_error "Failed to pull from origin (non-fast-forward?)"
            exit 1
          end

          ${lib.optionalString (upstreamFlake != null && upstreamInputName != null) ''
          #───────────────────────────────────────────────────────────────
          # Upstream Version Check
          #───────────────────────────────────────────────────────────────

          # Get current locked revision
          set -l current_rev (${lib.getExe pkgs.nix} flake metadata --json 2>/dev/null | ${lib.getExe pkgs.jq} -r '.locks.nodes["${upstreamInputName}"].locked.rev // empty')

          if test -z "$current_rev"
            log_error "Could not get current ${upstreamInputName} revision from flake.lock"
            exit 1
          end

          log "Current ${upstreamInputName} rev: $current_rev"

          # Get latest revision from upstream
          set -l latest_rev (${lib.getExe pkgs.nix} flake metadata "${upstreamFlake}" --json --refresh 2>/dev/null | ${lib.getExe pkgs.jq} -r '.revision // empty')

          if test -z "$latest_rev"
            log_error "Could not get latest ${upstreamInputName} revision"
            exit 1
          end

          log "Latest ${upstreamInputName} rev:  $latest_rev"

          set -g short_current (string sub -l 7 "$current_rev")
          set -g short_latest (string sub -l 7 "$latest_rev")
          set -g needs_update false

          if test "$current_rev" != "$latest_rev"
            set needs_update true
            log "New ${upstreamInputName} version available!"
          end
          ''}

          #───────────────────────────────────────────────────────────────
          # Cache Check
          #───────────────────────────────────────────────────────────────

          set -l needs_build false
          set -l missing_pkgs

          log "Checking if packages are in cache..."
          for pkg in $packages
            if not pkg_in_cache $pkg
              log "Package $pkg is NOT in cache"
              set needs_build true
              set -a missing_pkgs $pkg
            else
              log "Package $pkg is in cache"
            end
          end

          ${lib.optionalString (upstreamFlake != null) ''
          # If upstream updated, we need to build regardless of cache
          if $needs_update
            set needs_build true
            set missing_pkgs $packages  # Rebuild all when upstream changes
          end
          ''}

          # Exit if nothing to do
          if not $needs_build
            log "All packages are up to date and in cache, nothing to do"
            exit 0
          end

          #───────────────────────────────────────────────────────────────
          # Build Notification
          #───────────────────────────────────────────────────────────────

          ${lib.optionalString (upstreamFlake != null && upstreamInputName != null) ''
          if $needs_update
            log "Updating flake input and building packages..."
            notify "## $emoji New ${upstreamInputName} Update
          > **Rev:** \`$short_current\` → \`$short_latest\`
          > Building packages..."
          else
            log "Building missing packages: $missing_pkgs"
            notify "## $emoji Missing from Cache
          > Building: $missing_pkgs"
          end
          ''}

          ${lib.optionalString (upstreamFlake == null) ''
          log "Building missing packages: $missing_pkgs"
          notify "## $emoji Building ${shortName}
          > Packages: $missing_pkgs"
          ''}

          #───────────────────────────────────────────────────────────────
          # Update Flake Lock
          #───────────────────────────────────────────────────────────────

          ${lib.optionalString updateFlakeLock (
            if flakeInput != null then ''
          log "Running: nix flake update ${flakeInput}"
          ${lib.getExe pkgs.nix} flake update ${flakeInput}; or begin
            log_error "Failed to update ${flakeInput} input"
            notify "## ❌ Build Failed
          > Failed to update flake input"
            exit 1
          end
            '' else ''
          log "Running: nix flake update"
          ${lib.getExe pkgs.nix} flake update; or begin
            log_error "Failed to update flake inputs"
            notify "## ❌ Build Failed
          > Failed to update flake inputs"
            exit 1
          end
            ''
          )}

          #───────────────────────────────────────────────────────────────
          # Build Packages
          #───────────────────────────────────────────────────────────────

          log "Building packages (this may take a while)..."

          set -l failed_pkgs
          set -l success_pkgs

          for pkg in $packages
            log "Building $pkg..."
            if build_pkg $pkg
              log "Successfully built $pkg"
              set -a success_pkgs $pkg
            else
              log_error "Failed to build $pkg"
              set -a failed_pkgs $pkg
            end
          end

          #───────────────────────────────────────────────────────────────
          # Commit and Push
          #───────────────────────────────────────────────────────────────

          ${lib.optionalString updateFlakeLock ''
          if not git diff --quiet flake.lock
            log "Committing updated flake.lock..."

            git add flake.lock

            ${lib.optionalString (upstreamFlake != null && upstreamInputName != null) ''
            git commit -m "chore: update ${upstreamInputName} to $short_latest

          Auto-updated by ${name} service

          Previous: $short_current
          Current:  $short_latest

          Built: $success_pkgs"
            ''}

            ${lib.optionalString (upstreamFlake == null) ''
            git commit -m "chore: update flake inputs

          Auto-updated by ${name} service

          Built: $success_pkgs"
            ''}

            log "Pushing to origin..."
            git push origin $branch; or begin
              log_error "Failed to push to origin"
              notify "## ❌ Build Failed
          > Built packages but failed to push to origin"
              exit 1
            end
          end
          ''}

          #───────────────────────────────────────────────────────────────
          # Completion Notification
          #───────────────────────────────────────────────────────────────

          set -l pkg_list (string join "\n> • " $success_pkgs)

          if test (count $failed_pkgs) -eq 0
            ${lib.optionalString (upstreamFlake != null && upstreamInputName != null) ''
            notify "## ✅ ${description} Complete
          > **Rev:** \`$short_latest\`
          > • $pkg_list
          >
          > 📝 Run: \`nix flake lock --update-input mix-nix\` in dot.nix"
            ''}
            ${lib.optionalString (upstreamFlake == null) ''
            notify "## ✅ ${description} Complete
          > • $pkg_list
          >
          > 📝 Run: \`nix flake lock --update-input mix-nix\` in dot.nix"
            ''}
          else
            set -l failed_list (string join ", " $failed_pkgs)
            notify "## ⚠️ Some Builds Failed
          > **✓** $success_pkgs
          > **✗** $failed_list
          >
          > 📝 Run: \`nix flake lock --update-input mix-nix\` in dot.nix"
          end

          log "Build process complete!"
        '';
      };
    in
    {
      systemd.services.${name} = {
        inherit description;

        # Dependency ordering - wait for and don't run concurrently with another service
        after = lib.optional (after != null) "${after}.service";
        conflicts = lib.optional (after != null) "${after}.service";

        path = with pkgs; [
          fish
          git
          nix
          jq
          apprise
          openssh
          coreutils
        ];

        environment = {
          HOME = "/home/${serviceUser}";
          NIX_PATH = "nixpkgs=${pkgs.path}";
          GIT_SSH_COMMAND = "${pkgs.openssh}/bin/ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new";
        };

        serviceConfig = {
          Type = "oneshot";
          ExecStart = "${buildScript}";
          User = serviceUser;
          Group = "ryot";
          WorkingDirectory = repoPath;

          TimeoutStartSec = timeout;

          # Logging
          StandardOutput = "journal";
          StandardError = "journal";
          SyslogIdentifier = name;

          # Hardening
          NoNewPrivileges = true;
          PrivateTmp = true;
          ProtectSystem = "strict";
          ReadWritePaths = [
            repoPath
            "/nix/var"
          ];
          ProtectKernelTunables = true;
          ProtectKernelModules = true;
          ProtectControlGroups = true;
          RestrictRealtime = true;
          RestrictSUIDSGID = true;
          LockPersonality = true;
        };
      };

      systemd.timers.${name} = {
        description = "Timer for ${description}";
        wantedBy = [ "timers.target" ];

        timerConfig = {
          OnCalendar = schedule;
          Persistent = true;
          RandomizedDelaySec = "15min";
        };
      };
    };

  # System packages needed by build services
  systemPackages = with pkgs; [
    apprise
    git
    jq
  ];
}
