# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."ollama" = {
    image = "ollama/ollama:rocm";
    environment = {
      "HSA_OVERRIDE_GFX_VERSION" = "11.0.0";
      "OLLAMA_FLASH_ATTENTION" = "true";
      "OLLAMA_HOST" = "0.0.0.0:11434";
      "OLLAMA_KEEP_ALIVE" = "5m";
      "OLLAMA_MAX_LOADED_MODELS" = "2";
      "OLLAMA_MODELS" = "/models";
      "OLLAMA_NUM_PARALLEL" = "4";
      "OLLAMA_ORIGINS" = "*";
      "PYTORCH_HIP_ALLOC_CONF" = "expandable_segments:True";
      "PYTORCH_TUNABLEOP_ENABLED" = "1";
      "TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL" = "1";
    };
    volumes = [
      "/store/ollama/config:/root/.ollama:rw"
      "/store/ollama/models:/models:rw"
    ];
    ports = [
      "11434:11434/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--device=/dev/kfd:/dev/kfd:rwm"
      "--health-cmd=[\"ollama\", \"list\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=30s"
      "--health-timeout=10s"
      "--memory=34359738368b"
      "--network-alias=ollama"
      "--network=ai-network"
      "--security-opt=seccomp:unconfined"
      "--shm-size=17179869184"
    ];
  };
  systemd.services."docker-ollama" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ai-network.service"
    ];
    requires = [
      "docker-network-ai-network.service"
    ];
    partOf = [
      "docker-compose-ollama-root.target"
    ];
    wantedBy = [
      "docker-compose-ollama-root.target"
    ];
  };
  virtualisation.oci-containers.containers."open-webui" = {
    image = "ghcr.io/open-webui/open-webui:main";
    environment = {
      "ANONYMIZED_TELEMETRY" = "false";
      "DEFAULT_MODELS" = "llama3.2,mistral,codellama,qwen2.5-coder";
      "DEFAULT_USER_ROLE" = "user";
      "DO_NOT_TRACK" = "true";
      "ENABLE_COMMUNITY_SHARING" = "false";
      "ENABLE_RAG_WEB_SEARCH" = "true";
      "ENABLE_SIGNUP" = "false";
      "MODEL_FILTER_ENABLED" = "false";
      "OLLAMA_BASE_URL" = "http://ollama:11434";
      "RAG_EMBEDDING_MODEL" = "nomic-embed-text:latest";
      "SCARF_NO_ANALYTICS" = "true";
      "WEBUI_SECRET_KEY" = "";
    };
    volumes = [
      "/store/ollama/models:/app/backend/models:ro"
      "/store/open-webui:/app/backend/data:rw"
    ];
    ports = [
      "3000:8080/tcp"
    ];
    dependsOn = [
      "ollama"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"curl\", \"-f\", \"http://localhost:8080/health\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=40s"
      "--health-timeout=10s"
      "--network-alias=open-webui"
      "--network=ai-network"
    ];
  };
  systemd.services."docker-open-webui" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ai-network.service"
    ];
    requires = [
      "docker-network-ai-network.service"
    ];
    partOf = [
      "docker-compose-ollama-root.target"
    ];
    wantedBy = [
      "docker-compose-ollama-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-ai-network" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f ai-network";
    };
    script = ''
      docker network inspect ai-network || docker network create ai-network
    '';
    partOf = [ "docker-compose-ollama-root.target" ];
    wantedBy = [ "docker-compose-ollama-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-ollama-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
