{ pkgs, lib, ... }:
{
  # Containers
  virtualisation.oci-containers.containers."adguard" = {
    image = "adguard/adguardhome:latest";
    volumes = [
      "/etc/adguard/confdir:/opt/adguardhome/conf:rw"
      "/etc/adguard/workdir:/opt/adguardhome/work:rw"
      "/var/lib/acme:/opt/adguardhome/work/acme:ro"
    ];
    ports = [
      "5453:53/tcp" # Map to port 5453 to avoid conflict with dnsmasq
      "5453:53/udp" # Map to port 5453 to avoid conflict with dnsmasq
      "853:853/tcp" # DNS over TLS
      "3000:3000/tcp" # Web UI
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=adguard"
      "--network=adguard"  # Use clean 'adguard' network name
      "--network=newt"     # Keep newt connection for management
    ];
  };

  systemd.services."docker-adguard" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-adguard.service"
    ];
    requires = [
      "docker-network-adguard.service"
    ];
    partOf = [
      "docker-compose-adguard-root.target"
    ];
    wantedBy = [
      "docker-compose-adguard-root.target"
    ];
  };

  # Networks  
  systemd.services."docker-network-adguard" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f adguard";
    };
    script = ''
      docker network inspect adguard || docker network create adguard
    '';
    partOf = [ "docker-compose-adguard-root.target" ];
    wantedBy = [ "docker-compose-adguard-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-adguard-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
