{
  config,
  lib,
  pkgs,
  inputs,
  host,
  ...
}:

let
  cfg = config.theme;

  # Generate base16 YAML from matugen Material You colors using templates
  generateMatugenScheme =
    wallpaper: scheme: polarity:
    let
      templateFile = pkgs.writeText "matugen-base16-template.yaml" ''
        system: base16
        slug: matugen-material
        name: Matugen Material
        author: Generated by Matugen
        variant: ${polarity}
        palette:
          base00: "{{colors.background.default.hex}}"
          base01: "{{colors.surface_container_lowest.default.hex}}"
          base02: "{{colors.surface_container_low.default.hex}}"
          base03: "{{colors.outline_variant.default.hex}}"
          base04: "{{colors.on_surface_variant.default.hex}}"
          base05: "{{colors.on_surface.default.hex}}"
          base06: "{{colors.inverse_on_surface.default.hex}}"
          base07: "{{colors.surface_bright.default.hex}}"
          base08: "{{colors.error.default.hex}}"
          base09: "{{colors.tertiary.default.hex}}"
          base0A: "{{colors.secondary.default.hex}}"
          base0B: "{{colors.primary.default.hex}}"
          base0C: "{{colors.tertiary_container.default.hex}}"
          base0D: "{{colors.primary_container.default.hex}}"
          base0E: "{{colors.secondary_container.default.hex}}"
          base0F: "{{colors.error_container.default.hex}}"
      '';
    in
    pkgs.runCommand "matugen-base16-scheme.yaml"
      {
        nativeBuildInputs = [ inputs.matugen.packages.${pkgs.system}.default ];
      }
      ''
        cat > config.toml << EOF
        [config]

        [templates.base16]
        input_path = "${templateFile}"
        output_path = "$out"
        EOF

        matugen image ${wallpaper} \
          --type ${if scheme != null then scheme else "scheme-expressive"} \
          --mode ${polarity} \
          --config config.toml
      '';

  # Determine base16 scheme based on generator
  base16Config =
    if cfg.base16.generator == "stylix" then
      # Stylix: use file, pkg, or nothing (auto-generate)
      if cfg.base16.file != null then
        cfg.base16.file
      else if cfg.base16.pkg != null then
        "${pkgs.base16-schemes}/share/themes/${cfg.base16.pkg}.yaml"
      else
        # Don't set anything; let stylix auto-generate from wallpaper
        null
    else if cfg.base16.generator == "matugen" then
      {
        # Matugen: generate Material You colors from wallpaper
        yaml = "${generateMatugenScheme cfg.image cfg.base16.scheme cfg.polarity}";
        # Use IFD to bypass pure Nix YAML parser issues
        use-ifd = "auto";
      }
    else
      throw "Unknown base16 generator: ${cfg.base16.generator}";
in
{
  imports = [
    inputs.stylix.homeModules.stylix
  ];

  stylix = lib.mkIf cfg.enable (
    {
      enable = true;
      autoEnable = true;
      image = cfg.image;
      polarity = cfg.polarity;

      # Standard font configuration
      fonts = {
        serif = {
          package = pkgs.google-fonts.override { fonts = [ "Laila" ]; };
          name = "Laila";
        };

        sansSerif = {
          package = pkgs.lexend;
          name = "Lexend";
        };

        monospace = {
          package = pkgs.monocraft-nerd-fonts;
          name = "Monocraft";
        };

        emoji = {
          package = pkgs.noto-fonts-color-emoji;
          name = "Noto Color Emoji";
        };

        sizes = {
          applications = 12;
          desktop = 11;
          popups = 11;
          terminal = 12;
        };
      };

      targets = {
        gnome = {
          enable = true;
          useWallpaper = true;
        };
        vscode = {
          enable = false;
        };
      };
    }
    // lib.optionalAttrs (base16Config != null) {
      # Set base16 scheme based on generator and desktop environment
      # Only set if we have a value (null means let stylix auto-generate)
      base16Scheme = base16Config;
    }
  );

  home.pointerCursor = lib.mkIf cfg.enable {
    gtk.enable = true;
    package = cfg.pointer.package;
    name = cfg.pointer.name;
    size = cfg.pointer.size;
  };

  gtk = lib.mkIf cfg.enable {
    enable = true;

    iconTheme = {
      package = cfg.icon.package;
      name = cfg.icon.name;
    };
  };
}
