# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."explorer" = {
    image = "nxzai/explorer:latest";
    environment = {
      "GID" = "1004";
      "NODE_ENV" = "production";
      "UID" = "1000";
    };
    volumes = [
      "/store/explorer:/cache:rw"
      "/store:/mnt/store:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=explorer"
      "--network=explorer"
      "--expose=3000"
    ];
  };

  systemd.services."docker-explorer" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-explorer.service"
    ];
    requires = [
      "docker-network-explorer.service"
    ];
    partOf = [
      "docker-explorer.target"
    ];
    wantedBy = [
      "docker-explorer.target"
    ];
  };

  # Networks
  systemd.services."docker-network-explorer" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f explorer";
    };
    script = ''
      docker network inspect explorer || docker network create explorer
    '';
    partOf = [ "docker-explorer.target" ];
    wantedBy = [ "docker-explorer.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-explorer" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
