system: base16
slug: Invincible
name: Invincible
author: tophc7
variant: dark
palette:
  base00: "262A2B"
  base01: "2E3233"
  base02: "323739"
  base03: "464E53"
  base04: "ADE0FB"
  base05: "D4ECF1"
  base06: "E7F2EC"
  base07: "FAF7E6"
  base08: "EE2E00" # Red
  base09: "F7A94E" # Orange
  base0A: "FCEEA1" # Yellow
  base0B: "8DE364" # Green
  base0C: "59A3C0" # Cyan
  base0D: "2B57B6" # Blue
  base0E: "AC92BF" # Purple
  base0F: "EA5E79" # Magenta

# https://coolors.co/262a2b-2e3233-323739-464e53-ade0fb-d4ecf1-e7f2ec-faf7e6
# https://coolors.co/ee2e00-f7a94e-2b57b6-8de364-59a3c0-fceea1-ac92bf-ea5e79
