name: explorer
services:
    explorer:
        image: nxzai/explorer:latest
        container_name: explorer
        restart: unless-stopped
        expose:
            - "3000"
        environment:
            - NODE_ENV=production
            # Optional: match the container user/group to your host UID/GID
            - UID=1000
            - GID=1004
        volumes:
            - /fast/explorer:/cache
            # - /fast:/mnt/fast
            - /repo:/mnt/repo
            - /tank:/mnt/tank
